# Generated by Django 6.1 on 2026-08-30 16:05

import django.db.models.deletion
import partidos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='partidos.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[partidos.models.validar_precio_positivo]),
        ),
    ]
